# Generated by Django 2.1.4 on 2019-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_userprofile_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
