# Generated by Django 2.1.4 on 2019-01-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0004_auto_20190128_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
