# Generated by Django 2.1.7 on 2019-03-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0005_auto_20190129_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
