# Generated by Django 2.1.7 on 2019-03-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0006_auto_20190312_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
